name: publish to nuget
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Publish
      - name: publish on version change
        id: publish_nuget
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: CleanHandling/CleanHandling.csproj
          PACKAGE_NAME: CleanHandling
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
