name: publish to nuget
on:
   workflow_dispatch:
   
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./CleanHandling
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Add github source to nuget 
      run: dotnet nuget add source --username gumberss --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/OWNER/index.json"
    - name: Package
      if: github.ref == 'refs/heads/main'
      run: dotnet pack -c Release -o . CleanHandling.csproj
    - name: Publish nuget
      if: github.ref == 'refs/heads/main'
      run: dotnet nuget push *.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
    - name: Publish Github
      if: github.ref == 'refs/heads/main'
      run: dotnet nuget push *.nupkg -k ${{ secrets.GITHUB_TOKEN }} -s github
